---
language: python
cache: pip

env:
  matrix:
    - MOLECULE_DISTRO: debian10

install:
  # Install test dependencies.
  - python3 -m pip install ansible-lint molecule[docker,goss] yamllint

script:
  - molecule test -s docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
