---
- name: Import schleuder tasks
  ansible.builtin.import_tasks: schleuder.yml
  tags:
    - schleuder

- name: Import schleuder-cli tasks
  ansible.builtin.import_tasks: schleuder_cli.yml
  tags:
    - schleuder_cli
  when: schleuder_install_cli

- name: Flush handlers to ensure api is setup correct
  ansible.builtin.meta: flush_handlers

- name: Import tasks for schleuder Gitlab plugin
  ansible.builtin.import_tasks: schleuder_gitlab_ticket_plugin.yml
  tags:
    - schleuder_gitlab_ticket_plugin
  when: schleuder_install_gitlab_ticket_plugin
