---
- name: Install schleuder-cli
  ansible.builtin.apt:
    name: schleuder-cli
    state: "present"

- name: Ensure /root/.schleuder-cli/ is present
  ansible.builtin.file:
    path: "{{ schleuder_cli_path }}"
    state: directory
    owner: "root"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0600"

- name: Ensure schleuder-cli.yml is latest
  ansible.builtin.template:
    src: schleuder-cli/schleuder-cli.yml.j2
    dest: "{{ schleuder_cli_path }}/schleuder-cli.yml"
    owner: "root"
    group: "root"
    mode: "0600"
  notify: Restart schleuder-api-daemon
