---
- name: Install schleuder dependencies
  ansible.builtin.apt:
    name: "{{ __schleuder_dependencies }}"
    state: "present"
  vars:
    __schleuder_dependencies:
      - sqlite3

- name: Install tor
  ansible.builtin.apt:
    name: tor
    state: "present"
  when: schleuder_gpg_use_tor

- name: Install schleuder
  ansible.builtin.apt:
    name: "{{ __schleuder_packages }}"
    state: "present"
  vars:
    __schleuder_packages:
      - schleuder
  register: schleuder_install

- name: Ensure schleuder.yml is latest
  ansible.builtin.template:
    src: schleuder/schleuder.yml.j2
    dest: "/etc/schleuder/schleuder.yml"
    owner: "root"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0640"
  notify: Restart schleuder-api-daemon

- name: Ensure list-defaults.yml is latest
  ansible.builtin.template:
    src: schleuder/list-defaults.yml.j2
    dest: "/etc/schleuder/list-defaults.yml"
    owner: "root"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0640"

- name: Check if schleuder api is reachable
  ansible.builtin.uri:
    url: "https://{{ schleuder_api.host }}:{{ schleuder_api.port }}/status.json"
    validate_certs: False
    method: GET
    status_code: 200
    body_format: json
  when:
    - schleuder_install.changed # noqa: no-handler
    - not __testing | default(False)

- name: Ensure /var/lib/schleuder/.gnupg is present
  ansible.builtin.file:
    path: "/var/lib/schleuder/.gnupg"
    state: directory
    owner: "{{ schleuder_schleuder_user }}"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0700"
  when: schleuder_gpg_use_tor

- name: Ensure dirmngr.conf is latest
  ansible.builtin.template:
    src: schleuder/dirmngr.conf.j2
    dest: "/var/lib/schleuder/.gnupg/dirmngr.conf"
    owner: "{{ schleuder_schleuder_user }}"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0600"
  when: schleuder_gpg_use_tor
