---
- name: Install schleuder-gitlab-ticketing
  ansible.builtin.apt:
    name: "schleuder-gitlab-ticketing"
    state: "present"

- name: Ensure schleuder filter path is present
  ansible.builtin.file:
    path: /usr/local/lib/schleuder/filters/post_decryption
    owner: root
    group: staff
    mode: "0755"
    state: directory

- name: Ensure gitlab plugin config is latest
  ansible.builtin.template:
    src: schleuder/gitlab.yml.j2
    dest: /etc/schleuder/gitlab.yml
    owner: root
    group: "{{ schleuder_schleuder_user }}"
    mode: "0640"
