---
- name: Install schleuder and tor
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  register: schleuder_install
  with_items:
    - schleuder
    - tor

- name: Ensure schleuder.yml is latest
  ansible.builtin.template:
    src: schleuder/schleuder.yml.j2
    dest: "/etc/schleuder/schleuder.yml"
    owner: "root"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0640"
  notify: Restart schleuder-api-daemon

- name: Ensure list-defaults.yml is latest
  ansible.builtin.template:
    src: schleuder/list-defaults.yml.j2
    dest: "/etc/schleuder/list-defaults.yml"
    owner: "root"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0640"

- name: Check if schleuder api is reachable on fresh install
  ansible.builtin.uri:
    url: "https://{{ schleuder_api.host }}:{{ schleuder_api.port }}/status.json"
    validate_certs: false
    method: GET
    status_code: 200
    body_format: json
  changed_when: true
  when:
    - schleuder_install.changed # noqa: no-handler
    - not __testing | default(false)

- name: Ensure /var/lib/schleuder/.gnupg is present
  ansible.builtin.file:
    path: "/var/lib/schleuder/.gnupg"
    state: directory
    owner: "{{ schleuder_schleuder_user }}"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0700"

- name: Ensure dirmngr.conf is latest
  ansible.builtin.template:
    src: schleuder/dirmngr.conf.j2
    dest: "/var/lib/schleuder/.gnupg/dirmngr.conf"
    owner: "{{ schleuder_schleuder_user }}"
    group: "{{ schleuder_schleuder_user }}"
    mode: "0600"
