---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: schleuder-stretch64
    box: debian/stretch64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 3000, host: 3001"

  - name: schleuder-buster64
    box: debian/buster64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 3000, host: 3000"

lint: yamllint .

provisioner:
  name: ansible
  become: true

verifier:
  name: goss
