---
scenario:
  name: default

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: schleuder-stretch64
    box: debian/stretch64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 3000, host: 3001"
  - name: schleuder-buster64
    box: debian/buster64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 3000, host: 3000"

provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: False

lint:
  name: yamllint
  enabled: False

verifier:
  name: goss
  lint:
    name: yamllint
