---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: schleuder-bullseye64
    box: debian/bullseye64
    memory: 1024
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 3000, host: 3000"
  - name: schleuder-buster64
    box: debian/buster64
    memory: 1024
    cpus: 2

lint: yamllint .

provisioner:
  name: ansible
  become: true

verifier:
  name: goss
  enabled: false
