---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansible-role-schleuder
  vars:
    __testing: True
    schleuder_install_gitlab_ticket_plugin: True
    schleuder_gpg_use_tor: True
    schleuder_schleuder_web_api_host: "{{ ansible_default_ipv4.address }}"
