---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    exposed_ports:
      - 3000/tcp
    published_ports:
      - "0.0.0.0:3000:3000/tcp"

lint: yamllint .

provisioner:
  name: ansible
  playbooks:
    converge: ./converge.yml
    prepare: ../default/prepare.yml
    verify: ../default/verify.yml

verifier:
  name: goss
  directory: ../default/tests/
  enabled: yes
